In [1]:
#Load in libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
#Read in the cleaned data file
wine = pd.read_csv('wine_review.csv')
wine

Unnamed: 0  Type                              Name        Country  \
0               0  Rose        Mad Méditerranée Rosé 2019         France   
1               1  Rose                  Redoma Rosé 2019       Portugal   
2               2  Rose  Fantini Cerasuolo d'Abruzzo 2019          Italy   
3               3  Rose            Mount Hermon Rosé 2017         Israel   
4               4  Rose                La Villa Rosé 2018         France   
...           ...   ...                               ...            ...   
13829        8661   Red              6th Sense Syrah 2016  United States   
13830        8662   Red   Botrosecco Maremma Toscana 2016          Italy   
13831        8663   Red                   Haut-Médoc 2010         France   
13832        8664   Red                       Shiraz 2019      Australia   
13833        8665   Red  Portillo Cabernet Sauvignon 2016      Argentina   

                        Region                     Winery  Rating  \
0                 Méditerranée         Château Camparnaud     4.0   
1                        Douro                   Niepoort     3.9   
2                      Abruzzo                    Farnese     3.6   
3                      Galilee                     Hermon     3.4   
4                    Languedoc     Château La Sauvageonne     4.6   
...                        ...                        ...     ...   
13829                     Lodi       Michael David Winery     3.8   
13830          Maremma Toscana                Le Mortelle     4.0   
13831               Haut-Médoc  Château Cambon La Pelouse     3.7   
13832  South Eastern Australia                Yellow Tail     3.5   
13833                  Tunuyán                  Salentein     3.4   

       NumberOfRatings  Price  Year  
0                   25  10.11  2019  
1                   25  12.81  2019  
2                   25   5.60  2019  
3                   25  12.14  2017  
4                   25  68.95  2018  
...                ...    ...   ...  
13829              994  16.47  2016  
13830              995  20.09  2016  
13831              996  23.95  2010  
13832              998   6.21  2019  
13833              999   7.88  2016  

[13834 rows x 10 columns]

In [3]:
#I always get this weird extra row, so dropping that
wine = wine.drop(columns = ['Unnamed: 0'], axis = 1)
wine

Type                              Name        Country  \
0      Rose        Mad Méditerranée Rosé 2019         France   
1      Rose                  Redoma Rosé 2019       Portugal   
2      Rose  Fantini Cerasuolo d'Abruzzo 2019          Italy   
3      Rose            Mount Hermon Rosé 2017         Israel   
4      Rose                La Villa Rosé 2018         France   
...     ...                               ...            ...   
13829   Red              6th Sense Syrah 2016  United States   
13830   Red   Botrosecco Maremma Toscana 2016          Italy   
13831   Red                   Haut-Médoc 2010         France   
13832   Red                       Shiraz 2019      Australia   
13833   Red  Portillo Cabernet Sauvignon 2016      Argentina   

                        Region                     Winery  Rating  \
0                 Méditerranée         Château Camparnaud     4.0   
1                        Douro                   Niepoort     3.9   
2                      Abruzzo                    Farnese     3.6   
3                      Galilee                     Hermon     3.4   
4                    Languedoc     Château La Sauvageonne     4.6   
...                        ...                        ...     ...   
13829                     Lodi       Michael David Winery     3.8   
13830          Maremma Toscana                Le Mortelle     4.0   
13831               Haut-Médoc  Château Cambon La Pelouse     3.7   
13832  South Eastern Australia                Yellow Tail     3.5   
13833                  Tunuyán                  Salentein     3.4   

       NumberOfRatings  Price  Year  
0                   25  10.11  2019  
1                   25  12.81  2019  
2                   25   5.60  2019  
3                   25  12.14  2017  
4                   25  68.95  2018  
...                ...    ...   ...  
13829              994  16.47  2016  
13830              995  20.09  2016  
13831              996  23.95  2010  
13832              998   6.21  2019  
13833              999   7.88  2016  

[13834 rows x 9 columns]

In [8]:
#Want to look at correlation between rating and year first
year_corr = wine.corr()['Year']['Rating']
print('Correlation between Vintage Year and Rating is:{} '.format(year_corr))

Correlation between Vintage Year and Rating is:0.04312074407009118 


In [9]:
#Look at unique counts for rating
rating = wine.groupby("Rating")['Name'].count()
rating

Rating
2.2       1
2.5       2
2.6       2
2.7       3
2.8       8
2.9       8
3.0      32
3.1      48
3.2     142
3.3     281
3.4     469
3.5     824
3.6    1347
3.7    1663
3.8    2065
3.9    1792
4.0    1418
4.1    1339
4.2    1034
4.3     620
4.4     364
4.5     202
4.6     130
4.7      31
4.8       8
4.9       1
Name: Name, dtype: int64

In [24]:
#Look up the row by rating of 4.9
vintage_high = wine.loc[wine['Rating'] == 4.9]
vintage_high

Type                                           Name Country  \
1945  White  Montrachet Grand Cru Marquis de Laguiche 2017  France   

                    Region          Winery  Rating  NumberOfRatings   Price  \
1945  Montrachet Grand Cru  Joseph Drouhin     4.9               34  681.37   

      Year  
1945  2017

In [23]:
#Look up row by rating of 2.2
vintage_low = wine.loc[wine['Rating'] == 2.2]
vintage_low

Type                      Name Country        Region    Winery  Rating  \
3281  White  Greca Terra Retsina N.V.  Greece  Peloponnesos  Tsantali     2.2   

      NumberOfRatings  Price  Year  
3281               77   5.35     0

In [22]:
#One more look at rating for 4.8
second_high = wine.loc[wine['Rating'] == 4.8]
second_high

Type                                               Name  \
77      Rose                                   Garrus Rosé 2018   
2414   White                            Ermitage de l'Orée 2004   
6119     Red                     Barolo Riserva Monfortino 2013   
8588     Red                                             G 2015   
8915     Red  Beckstoffer Las Piedras Vineyard Cabernet Sauv...   
9199     Red                L'Ermita Velles Vinyes Priorat 2008   
13241    Red                                       Toscana 2016   
13254    Red                        Veneto Alzero Cabernet 2009   

             Country             Region                Winery  Rating  \
77            France  Côtes de Provence     Château d'Esclans     4.8   
2414          France          Hermitage         M. Chapoutier     4.8   
6119           Italy             Barolo      Giacomo Conterno     4.8   
8588    South Africa       Western Cape        4G Wine Estate     4.8   
8915   United States         St. Helena            Paul Hobbs     4.8   
9199           Spain            Priorat       Álvaro Palacios     4.8   
13241          Italy            Toscana               Masseto     4.8   
13254          Italy             Veneto  Quintarelli Giuseppe     4.8   

       NumberOfRatings    Price  Year  
77                  36   109.00  2018  
2414                44   189.95  2004  
6119               132  1115.50  2013  
8588                28   463.03  2015  
8915                30   368.47  2015  
9199                32   672.60  2008  
13241               85   960.17  2016  
13254               85   324.95  2009

In [21]:
#Final look at ratings for 2.5
medium_low = wine.loc[wine['Rating'] == 2.5]
medium_low

Type                     Name       Country     Region  \
10166  Red  Cabernet Sauvignon 2016        France  Pays d'Oc   
11503  Red  Cabernet Sauvignon 2018  South Africa  Cape Town   

                  Winery  Rating  NumberOfRatings  Price  Year  
10166            Fortant     2.5               40   8.29  2016  
11503  Cape Town Wine Co     2.5               55   7.50  2018

```
Looked at the row in the dataframe that had the highest rating at 4.9, which gave me Montrachet Grand Cru Marquis de Laguiche 2017. I did double check this against the excel file as well and it was correct. Not sure why the 1945 keeps showing up, but 2017 was the vintage year. This means that year doesn't always equal higher rating. The highest rated vintage came from 2017 which is fairly recent, while the lowest rated wine is from a N.V. meaning it is a combination of several vintages.I then wanted to look at the rows for the second highest rating at 4.8, which again all fell within the 2000's. So for this question I would say year doesn't always equal higher rating.
```

In [17]:
#Now I'd like to look at price. Using describe to see max price
wine.describe()

Rating  NumberOfRatings         Price          Year
count  13834.000000     13834.000000  13834.000000  13834.000000
mean       3.865664       428.322466     33.024850   1907.135391
std        0.296427      1838.413812     70.899893    454.699562
min        2.200000        25.000000      3.150000      0.000000
25%        3.700000        56.000000      9.902500   2014.000000
50%        3.900000       129.000000     15.950000   2016.000000
75%        4.100000       336.000000     32.500000   2018.000000
max        4.900000     94287.000000   3410.790000   2020.000000

In [25]:
#Look up the row for the highest price shown
high_price = wine.loc[wine['Price'] == 3410.79]
high_price

Type          Name Country   Region  Winery  Rating  NumberOfRatings  \
7512  Red  Pomerol 2012  France  Pomerol  Pétrus     4.7              204   

        Price  Year  
7512  3410.79  2012

In [32]:
#Looking to see if this winery has others in the dataset
high_winery = wine.loc[wine['Winery'] == 'Pétrus']
high_winery

Type          Name Country   Region  Winery  Rating  NumberOfRatings  \
7512  Red  Pomerol 2012  France  Pomerol  Pétrus     4.7              204   

        Price  Year  
7512  3410.79  2012

In [26]:
#Look up the row for the lowest price shown
low_price = wine.loc[wine['Price'] == 3.15]
low_price

Type                              Name Country  Region     Winery  \
497  Sparkling            Frizzantino Dolce N.V.   Italy  Emilia  Gualtieri   
658  Sparkling  Lambrusco dell’Emilia Dolce N.V.   Italy  Emilia  Gualtieri   

     Rating  NumberOfRatings  Price  Year  
497     4.2               43   3.15     0  
658     3.8              106   3.15     0

In [30]:
#Looking to see if winery has any others in the dataset
low_winery = wine.loc[wine['Winery'] == 'Gualtieri']
low_winery

Type                              Name Country  Region     Winery  \
497  Sparkling            Frizzantino Dolce N.V.   Italy  Emilia  Gualtieri   
658  Sparkling  Lambrusco dell’Emilia Dolce N.V.   Italy  Emilia  Gualtieri   

     Rating  NumberOfRatings  Price  Year  
497     4.2               43   3.15     0  
658     3.8              106   3.15     0

```
Looking at the price along with the rating for these wines it looks like higher price does not always equal to higher rating. Looking at Frizzantino Dolce N.V. the price is 3.15 euros but the rating is on the higher range at 4.2. However, the Pomerol 2012 has the highest price at 3,410.79 euros and also has a high rating at 4.7. Looking at the rows I looked at previously with ratings, the higher ratings also had higher prices. So I feel confident enough in saying that if a wine has a higher price it wil most likely have a higher rating. 
```